# Vectors, Matrices, and Arrays

## Creating a Vector

In [1]:
#load library
import numpy as np

#Create a vector as a row
vector_row = np.array([1, 2, 3])

#Create a vector as a column
vector_colum = np.array([[1],
                         [2],
                         [3]])

print(vector_row)
print('')
print(vector_colum)

[1 2 3]

[[1]
 [2]
 [3]]


## Creating a Matrix

In [2]:
#load library
import numpy as np

#Create a matrix
matrix = np.array([[1, 2],
                  [1, 2],
                  [1, 2]])

print(matrix)

[[1 2]
 [1 2]
 [1 2]]


In [3]:
# not recommended
import numpy as np
matrix_object = np.mat([[1, 2],
                       [1, 2],
                       [1, 2]])
print(matrix_object)

[[1 2]
 [1 2]
 [1 2]]


## Creating a Sparse Matrix

In [4]:
#load library
import numpy as np
from scipy import sparse

#Create a matrix
matrix = np.array([[0, 0],
                  [0, 1],
                  [3, 0]])

#Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

#View sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [5]:
#load library
import numpy as np

#Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

#View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


## Selecting Elements

In [6]:
#load library
import numpy as np

#Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

#Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#Select third element of  vector
print('Third element of vector:  ', vector[2])

#Select second row, second column
print('Second row, second column:', matrix[1,1])

print('')
print('1.', vector[:])
print('2.', vector[:3])
print('3.', vector[3:])
print('4.', vector[-1])
print('5.', matrix[:2,:])
print('6.', matrix[:,1:2])

Third element of vector:   3
Second row, second column: 5

1. [1 2 3 4 5 6]
2. [1 2 3]
3. [4 5 6]
4. 6
5. [[1 2 3]
 [4 5 6]]
6. [[2]
 [5]
 [8]]


## Descibing a Matrix

In [7]:
#load library
import numpy as np

#Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

#View number of rows and columns
print('Number of rows and columns:', matrix.shape)

#View number of elements (rows * columns)
print('    Number of elements:    ', matrix.size)

#View number of dimensions
print('   Number of dimensions:   ', matrix.ndim)

Number of rows and columns: (3, 4)
    Number of elements:     12
   Number of dimensions:    2


## Applying Operations to Elements

In [8]:
#load library
import numpy as np

#Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                 [7, 8, 9]])

#Create function that adds 100 to something
add_100 = lambda i:i + 100

#Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

#Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [9]:
#load library
import numpy as np

#Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                 [7, 8, 9]])

#Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## Finding the Maximum and Minimum Values

In [10]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return maximum element
print(np.max(matrix))

# Return minimum element
print(np.min(matrix))

# Find maximum element in each column
print('')
print(np.max(matrix, axis=0))

# Find maximum element in each row
print(np.max(matrix, axis=1))

9
1

[7 8 9]
[3 6 9]


## Calculating the Average, Variance, and Standard Deviation

In [11]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return mean
print(np.mean(matrix))

# Return variance
print(np.var(matrix))

# Return standard deviation
print(np.std(matrix))

# Find the mean value in each column
print(np.mean(matrix, axis=0))

5.0
6.666666666666667
2.581988897471611
[4. 5. 6.]


## Reshaping Arrays

In [12]:
#Load library
import numpy as np

# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Reshape matrix into 2x6 matrix
print(matrix.reshape(2, 6))

print('')
print(matrix.size)
print(matrix.reshape(1, -1))
print(matrix.reshape(12))  #11 or 13 is not correct

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

12
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Transposing a Vector or Matrix

In [13]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose matrix
print(matrix.T)

# Transpose vector
print('')
print(np.array([1, 2, 3, 4, 5, 6]))
print(np.array([1, 2, 3, 4, 5, 6]).T)

# Tranpose row vector
print('')
print(np.array([[1, 2, 3, 4, 5, 6]]))
print(np.array([[1, 2, 3, 4, 5, 6]]).T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[1 2 3 4 5 6]
[1 2 3 4 5 6]

[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


## Flattening a Matrix

In [14]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flatten matrix
print(matrix.flatten())

print(matrix.reshape(1, -1))

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]


## Finding the Rank of a Matrix

In [15]:
#Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# Return matrix rank
np.linalg.matrix_rank(matrix)

2

## Calculating the Determinant

In [16]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return determinant of matrix
np.linalg.det(matrix)

0.0

## Getting the Diagonal of a Matrix

In [17]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return diagonal elements
print(matrix.diagonal())

# Return diagonal one above the main diagonal
print(matrix.diagonal(offset=1))

# Return diagonal one below the main diagonal
print(matrix.diagonal(offset=-1))

[1 4 9]
[2 6]
[2 8]


## Calculating the Trace of a Matrix

In [18]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return trace
print(matrix.trace())

# Return diagonal and sum elements
print(sum(matrix.diagonal()))

14
14


## Finding Eigenvalues and Eigenvectors

In [19]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# View eigenvalues
print('eigenvalues:', eigenvalues, '\n')

# View eigenvectors
print('eigenvectors:')
print(eigenvectors)

eigenvalues: [13.55075847  0.74003145 -3.29078992] 

eigenvectors:
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


## Calculating Dot Products

In [20]:
# Load library
import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
print('Dot Products:', np.dot(vector_a, vector_b))

# Calculate dot product
print(vector_a @ vector_b)

Dot Products: 32
32


## Adding and Subtracting Matrices

In [21]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
print('Add:')
print(np.add(matrix_a, matrix_b))

# Subtract two matrices
print('Subtract:')
print(np.subtract(matrix_a, matrix_b))

# Add two matrices
matrix_a + matrix_b

Add:
[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]
Subtract:
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

## Multiplying Matrices

In [22]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1],
                     [1, 2]])

# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

# Multiply two matrices
print('Multipy:')
print(np.dot(matrix_a, matrix_b))

# Multiply two matrices
print('')
print('a @ b:')
print(matrix_a @ matrix_b)

# Multiply two matrices element-wise
print('')
print('a * b:')
print(matrix_a * matrix_b)

Multipy:
[[2 5]
 [3 7]]

a @ b:
[[2 5]
 [3 7]]

a * b:
[[1 3]
 [1 4]]


## Inverting a Matrix

In [23]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])

# Calculate inverse of matrix
print('Inverse:')
print(np.linalg.inv(matrix))

# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

Inverse:
[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


array([[1., 0.],
       [0., 1.]])

## Generating Random Values

In [24]:
# Load library
import numpy as np

# Set seed
np.random.seed(0)

# Generate three random floats between 0.0 and 1.0
print(np.random.random(3))
print('')

# Generate three random integers between 1 and 10
print(np.random.randint(0, 11, 3))

# Draw three numbers from a normal distribution with mean 0.0 and standard deviation of 1.0
print(np.random.normal(0.0, 1.0, 3))

# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
print(np.random.logistic(0.0, 1.0, 3))

# Draw three numbers greater than or equal to 1.0 and less than 2.0
print(np.random.uniform(1.0, 2.0, 3))

[0.5488135  0.71518937 0.60276338]

[3 7 9]
[-1.42232584  1.52006949 -0.29139398]
[-0.98118713 -0.08939902  1.46416405]
[1.47997717 1.3927848  1.83607876]
